name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        type: boolean
        default: false
  push:
    tags:
      - 'v*'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
      release_type: ${{ steps.meta.outputs.release_type }}
      build_time: ${{ steps.meta.outputs.build_time }}
      is_prerelease: ${{ steps.meta.outputs.is_prerelease }}
      tag_name: ${{ steps.meta.outputs.tag_name }}
      release_name: ${{ steps.meta.outputs.release_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Generate metadata
        id: meta
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
            IS_PRERELEASE="${{ github.event.inputs.prerelease }}"
            TAG_NAME="$VERSION"
            RELEASE_NAME="BIP38CLI $VERSION"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
            IS_PRERELEASE="false"
            TAG_NAME="$VERSION"
            RELEASE_NAME="BIP38CLI $VERSION"
          fi
          
          BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          RELEASE_TYPE="release"
          
          if [[ "$IS_PRERELEASE" == "true" ]]; then
            RELEASE_TYPE="prerelease"
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "release_type=$RELEASE_TYPE" >> $GITHUB_OUTPUT
          echo "build_time=$BUILD_TIME" >> $GITHUB_OUTPUT
          echo "is_prerelease=$IS_PRERELEASE" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "release_name=$RELEASE_NAME" >> $GITHUB_OUTPUT
          
          echo "Version: $VERSION"
          echo "Release Type: $RELEASE_TYPE"
          echo "Build Time: $BUILD_TIME"
          echo "Is Prerelease: $IS_PRERELEASE"

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ needs.prepare.outputs.version }}
          BUILD_TIME: ${{ needs.prepare.outputs.build_time }}
        run: |
          mkdir -p dist
          
          BINARY_NAME="bip38cli"
          if [[ "$GOOS" == "windows" ]]; then
            BINARY_NAME="bip38cli.exe"
          fi
          
          cd core
          go build -ldflags "-X main.version=$VERSION -X main.buildTime=$BUILD_TIME" \
            -o "../dist/${BINARY_NAME}" \
            ./cmd/bip38cli

      - name: Create archive
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          VERSION: ${{ needs.prepare.outputs.version }}
        run: |
          cd dist
          
          BINARY_NAME="bip38cli"
          if [[ "$GOOS" == "windows" ]]; then
            BINARY_NAME="bip38cli.exe"
            ARCHIVE_NAME="bip38cli-${VERSION}-${GOOS}-${GOARCH}.zip"
            zip "$ARCHIVE_NAME" "$BINARY_NAME"
          else
            ARCHIVE_NAME="bip38cli-${VERSION}-${GOOS}-${GOARCH}.tar.gz"
            tar -czf "$ARCHIVE_NAME" "$BINARY_NAME"
          fi
          
          echo "archive_name=$ARCHIVE_NAME" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bip38cli-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/${{ env.archive_name }}

  release:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.prepare.outputs.tag_name }}
          name: ${{ needs.prepare.outputs.release_name }}
          body: |
            ## BIP38CLI ${{ needs.prepare.outputs.version }}
            
            A command-line tool for BIP38 Bitcoin private key encryption.
            
            ### Downloads
            Choose the appropriate binary for your platform:
            
            - **Linux (amd64)**: `bip38cli-${{ needs.prepare.outputs.version }}-linux-amd64.tar.gz`
            - **Linux (arm64)**: `bip38cli-${{ needs.prepare.outputs.version }}-linux-arm64.tar.gz`
            - **macOS (Intel)**: `bip38cli-${{ needs.prepare.outputs.version }}-darwin-amd64.tar.gz`
            - **macOS (Apple Silicon)**: `bip38cli-${{ needs.prepare.outputs.version }}-darwin-arm64.tar.gz`
            - **Windows (amd64)**: `bip38cli-${{ needs.prepare.outputs.version }}-windows-amd64.zip`
            
            ### Installation
            
            **Linux/macOS:**
            ```bash
            # Download and extract
            wget https://github.com/carlosrabelo/bip38cli/releases/download/${{ needs.prepare.outputs.version }}/bip38cli-${{ needs.prepare.outputs.version }}-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m).tar.gz
            tar -xzf bip38cli-${{ needs.prepare.outputs.version }}-$(uname -s | tr '[:upper:]' '[:lower:]')-$(uname -m).tar.gz
            
            # Install to /usr/local/bin
            sudo mv bip38cli /usr/local/bin/
            
            # Or install to user directory
            mkdir -p ~/.local/bin
            mv bip38cli ~/.local/bin/
            export PATH="$HOME/.local/bin:$PATH"
            ```
            
            **Windows:**
            ```powershell
            # Download and extract
            Invoke-WebRequest -Uri "https://github.com/carlosrabelo/bip38cli/releases/download/${{ needs.prepare.outputs.version }}/bip38cli-${{ needs.prepare.outputs.version }}-windows-amd64.zip" -OutFile "bip38cli.zip"
            Expand-Archive -Path "bip38cli.zip" -DestinationPath "."
            
            # Add to PATH or move to desired location
            ```
            
            ### Verification
            
            ```bash
            bip38cli --version
            # Expected output: bip38cli ${{ needs.prepare.outputs.version }} (built: ${{ needs.prepare.outputs.build_time }})
            ```
            
            ### Changelog
            
            ${{ needs.prepare.outputs.release_type == 'prerelease' && 'This is a prerelease version for testing purposes.' || 'Stable release with the latest features and bug fixes.' }}
            
            ---
            
            Build time: ${{ needs.prepare.outputs.build_time }}
          draft: false
          prerelease: ${{ needs.prepare.outputs.is_prerelease }}
          files: |
            artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
